# version: '3.7' 
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      # - '8080:8080'
      - '8085:8080'
    volumes:
      - ./etc:/etc/trino
      - ./conf:/etc/trino/conf
    networks:
      # - trino-network
      trino-network:

  postgres:
    image: 'postgres:11'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      # - trino-network
      # trino-network:
      - trino-network
      - iceberg_net   # also share with spark & airflow

  hive-metastore:
    image: 'my-hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres
    networks:
      # - trino-network
      trino-network:

# Adding Spark
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      trino-network:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./data:/home/iceberg/data
      - ./jars/postgresql-42.7.7.jar:/opt/spark/jars/postgresql-42.7.7.jar 
      - ./libs:/home/iceberg/libs
      - ./mne_configs:/home/iceberg/mne_configs
      - ./src:/home/iceberg/src
    environment:
      - PYTHONPATH=/home/iceberg
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    networks:
      trino-network:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      trino-network:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      trino-network:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
# Airflow 
  airflow:
    # image: apache/airflow:2.9.2
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - postgres
      - spark-iceberg
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      # Airflow metadata DB points to same postgres container (different DB name!)
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=UTC
      - AIRFLOW__WEBSERVER__PORT=8090     # avoid Spark’s 8080 conflict
      - PYTHONPATH=/home/airflow/libs:/home/iceberg
      - AIRFLOW__CORE__FERNET_KEY=1J-OxNE5XgZilVAdFE7Lk1GYdKymHhJqa6rqaH0myWY=
      - AIRFLOW__WEBSERVER__SECRET_KEY=/FQcb906qV7xB02pRTTAZw==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./libs:/home/airflow/libs       # your shared connectors
      - ./notebooks:/home/iceberg/notebooks/
      - ./libs:/home/iceberg/libs
      - ./mne_configs:/home/iceberg/mne_configs
      - ./src:/home/iceberg/src
    ports:
      - "8090:8090"   # Airflow UI
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        exec airflow webserver --port 8090
      "
    networks:
      - iceberg_net
      - trino-network

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__FERNET_KEY=1J-OxNE5XgZilVAdFE7Lk1GYdKymHhJqa6rqaH0myWY=
      - AIRFLOW__WEBSERVER__SECRET_KEY=/FQcb906qV7xB02pRTTAZw==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./libs:/home/airflow/libs
      - ./notebooks:/home/iceberg/notebooks
      - ./libs:/home/iceberg/libs
      - ./mne_configs:/home/iceberg/mne_configs
      - ./src:/home/iceberg/src
    networks:
      - iceberg_net
      - trino-network

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    depends_on:
      - postgres
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres:5432/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__PORT=8090
      - AIRFLOW__CORE__FERNET_KEY=1J-OxNE5XgZilVAdFE7Lk1GYdKymHhJqa6rqaH0myWY=
      - AIRFLOW__WEBSERVER__SECRET_KEY=/FQcb906qV7xB02pRTTAZw==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./libs:/home/airflow/libs
      - ./notebooks:/opt/airflow/dags/notebooks
      - ./libs:/home/iceberg/libs
      - ./mne_configs:/home/iceberg/mne_configs
      - ./src:/home/iceberg/src
    networks:
      - iceberg_net
      - trino-network
# AF

volumes:
  minio-data:
    driver: local
  postgres_data: 

networks:
  # trino-network:
  #   # driver: bridge
  iceberg_net:
    # external: true
  trino-network:
    # external: true