# version: '3.7' 
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
      - ./conf:/etc/trino/conf
    networks:
      - trino-network

  postgres:
    image: 'postgres:11'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hive_db
    networks:
      - trino-network

  hive-metastore:
    image: 'my-hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - trino-network

  # spark:
  #   image: apache/spark-py:3.5.0
  #   container_name: spark
  #   hostname: spark
  #   environment:
  #     - SPARK_NO_DAEMONIZE=true
  #   ports:
  #     - "7077:7077"   # Spark master
  #     - "8081:8081"   # Spark web UI
  #   command: bin/spark-class org.apache.spark.deploy.master.Master --host spark
  #   networks:
  #     - trino-network
  #   volumes:
  #     - ./spark-apps:/opt/spark-apps
  #     - ./spark-data:/opt/spark-data
  #     - ./jars:/opt/spark/jars   # mount hadoop-aws + aws-sdk jars here

  # spark-master:
  #   image: bitnami/spark:3.5.0
  #   hostname: spark-master
  #   container_name: spark-master
  #   environment:
  #     - SPARK_MODE=master
  #   ports:
  #     - "7077:7077"
  #     - "8081:8080"
  #   networks:
  #     - trino-network
  #   volumes:
  #     - ./jars:/opt/spark/jars

  # spark-worker:
  #   image: bitnami/spark:3.5.0
  #   hostname: spark-worker
  #   depends_on:
  #     - spark-master
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #   networks:
  #     - trino-network
  #   volumes:
  #     - ./jars:/opt/spark/jars

volumes:
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge
